### ISSUE TITLE
建议添加内网Endpoint上传功能

### ISSUE THREAD

**Issue by Master-Xia** [jacobcyl/Aliyun-oss-storage#10]
建议添加ECS访问的内网Endpoint，如果设置内网Endpoint，则由内网Endpoint（oss-cn-hangzhou-internal.aliyuncs.com）上传，外网Endpoint（oss-cn-hangzhou.aliyuncs.com）下载。如果未添加内网Endpoint，全部由外网Endpoint上传、下载。

**Comment by jacobcyl** [comment]
感谢你的建议，抽空把这个添加上去。

**Comment by jacobcyl** [comment]
2.0.4版本已经增加了内网 endpoint_internal支持，可在配置文件中配置使用，经测试暂无发现问题

**Comment by Master-Xia** [comment]
谢谢，前一段时间搞前端去了，没有及时回复。
我注意到一处小问题：
**AliOssAdapter**中`use Dingo\Api\Contract\Transformer\Adapter;`并没有调用。

**Comment by hao-li** [comment]
请问这个内网上传的问题修复了吗？
> 由于内网上传有点小问题未解决，请大家暂时不要使用内网节点上传，正在与阿里技术沟通中

https://github.com/jacobcyl/Aliyun-oss-storage/blob/9527fe90aaef0a7ac68e426f7caf4b5b74f08ed7/readme.md#L37
