### ISSUE TITLE
建议不要捕获错误

### ISSUE THREAD

**Issue by harde** [jacobcyl/Aliyun-oss-storage#18]
在大多数能引发OssException的地方，都被Catch，然后简单的return false了。
但是这样在项目运行时，可能会引发一些潜在问题。

另外：在listContents方法中，调用了listDirObjects，但是当listDirObjects发生错误时，没有做异常判定。导致异常抛出。

不捕获OssException是不是更好一些？

**Comment by jacobcyl** [comment]
后续会考虑采纳您的建议修改

**Comment by jacobcyl** [comment]
其实这个权衡考虑，为什么要捕获异常，主要是异常中经常包含一些敏感信息，例如bucket名称，所以采用输出Log错误记录，且返回false的方案。

或许今后会考虑重构 OssException 异常信息，直接抛出异常其实是更加符合规范的。

你提到的listContents问题中，我已修改为抛出异常了，这个我觉得抛出异常会更加合适，感谢你的建议
