### ISSUE TITLE
支持laravel5.3吗

### ISSUE THREAD

**Issue by qinghua0706** [jacobcyl/Aliyun-oss-storage#21]
在laravel5.3中使用时putFile方法时会报错。
下面是5.3中FilesystemAdapter.php中putFile方法
`    public function putFile($path, $file, $visibility = null)
    {
        return $this->putFileAs($path, $file, $file->hashName(), $visibility);
    }`
其中第二个参数是UploadedFile类型，而文档中写的是传string类型

**Comment by jacobcyl** [comment]
可以提个 PR 吗？因为近期项目太忙，一时没太多时间做5.3的，不知道是否支持

**Comment by qinghua0706** [comment]
5.3能用的，是我代码写得不对，感谢你的分享，我关掉这个。
