### ISSUE TITLE
$filePath 

### ISSUE THREAD

**Issue by zongmi** [jacobcyl/Aliyun-oss-storage#32]
`public function getUrl( $path )
    {
        if (!$this->has($path)) throw new FileNotFoundException($filePath.' not found');
        return ( $this->ssl ? 'https://' : 'http://' ) . ( $this->isCname ? ( $this->cdnDomain == '' ? $this->endpoint : $this->cdnDomain ) : $this->bucket . '.' . $this->endPoint ) . '/' . ltrim($path, '/');
    }`

**Comment by zongmi** [comment]
public function getUrl( $path )
    {
        if (!$this->has($path)) throw new FileNotFoundException($filePath.' not found');
        return ( $this->ssl ? 'https://' : 'http://' ) . ( $this->isCname ? ( $this->cdnDomain == '' ? $this->endpoint : $this->cdnDomain ) : $this->bucket . '.' . $this->endPoint ) . '/' . ltrim($path, '/');
    }

**Comment by ziyeziye** [comment]
修复了getUrl文件不存在报错的问题，和使用自定义域名(cdn)上传报错的问题:
https://github.com/ziyeziye/Aliyun-oss-storage
