### ISSUE TITLE
putFile 提示 Call to a member function hashName() on string

### ISSUE THREAD

**Issue by MADAOCOO** [jacobcyl/Aliyun-oss-storage#45]
环境laravel5.5
Storage::disk('oss')->putFile($filename, storage_path('app/public/文件名')))

**Comment by siwesley** [comment]
找到问题的原因了吗

**Comment by niefufeng** [comment]
。。。我特么试了两个小时，一直报这个错，因为我哪儿配置没对，看到大家都有这个问题我就放心了

**Comment by jasonfish568** [comment]
顶楼上的，我感觉是laravel升级后，有个function里自动去读取这个hashName

```
$oss_client=new OssClient('access_id', 'access_key', 'endpoint',false);
$oss_client->uploadFile('bucket_id', 'destination_path', storage_path('app/local_path'));
```

以上的用法不会产生问题，但是不是长久之计。如若有人解决了这个问题还请发出来。另外，这个repo好像已经被遗弃了

**Comment by hellowords** [comment]
使用`putFileAs()`就可以了
`\Storage::putFileAs($path, $request->file('file'), $request->file('file')->getClientOriginalName())`

**Comment by leiliang520130** [comment]
@txlife 谢谢大佬提供思路,这样可以先将就用,老项目怎么的老火

**Comment by jasonfish568** [comment]
这个库停更了 我们已经move到summergeorge的repo了，这个问题我记得是直接就被后续PR修复了

fk <notifications@github.com> 于 2020年9月7日周一 下午6:49写道：
