### ISSUE TITLE
私有云文件地址如何获取

### ISSUE THREAD

**Issue by shenglin-php** [jacobcyl/Aliyun-oss-storage#47]
用Storage::url(); 获取私有云的文件地址，异常提示文件不存在FileNotFoundException

**Comment by feikai2012** [comment]
@shenglin-php 修改AliOssAdapter  geturl方法$this->client->signUrl($this->bucket, $path);作者方法没有写完善。只能获取公开链接

**Comment by summergeorge** [comment]
代码实现了$client->signUrl()方法，提交了requests给作者，可以参考使用。 #53

**Comment by shenglin-php** [comment]
3Q
