### ISSUE TITLE
如果oss设置了无效的回源地址会导致错误

### ISSUE THREAD

**Issue by zhylninc** [jacobcyl/Aliyun-oss-storage#5]
因put时需先检验是否存在，导致超时报错

**Comment by jacobcyl** [comment]
sorry， 这段时间忙着没看到Issues， @zhylninc  你指的是 Storage::put() 方法吗， put 方法不需要调用回源地址吧，回源地址是指你请求的资源在cdn中不存在时，才会通过回源地址加载存储在oss的文件。能详细说明一下您的问题吗。
