### ISSUE TITLE
This driver does not support retrieving URLs.

### ISSUE THREAD

**Issue by idone-wangqiang** [jacobcyl/Aliyun-oss-storage#7]
现在不支持上传成功后，直接获取url吗？

**Comment by jacobcyl** [comment]
@idone-wangqiang url这个需要你自己配置，因为每个人的情况不一样，比如你如果使用了CDN绑定，那么完整的URL就是你绑定的CDN加上你上传时使用的path路径。因为url其实就是你上传时使用的路径指定的。所以没有必要设置返回URL。假设你没有使用CDN，那么可以使用OSS分配给你的节点域名+你上传的文件路径组合成URL。另外OSS还有图片样式属性，可以在url后面使用。

**Comment by 327** [comment]
好的，非常感谢您的付出

**Comment by jacobcyl** [comment]
不客气
