### ISSUE TITLE
内网上传现在是否可用？

### ISSUE THREAD

**Issue by zongmi** [jacobcyl/Aliyun-oss-storage#78]
内网上传现在是否可用？

**Comment by zongmi** [comment]
目前遇见上传远程图片[微信头像url]到ｏｓｓ很慢，每张２０秒，其他网络图片就是秒传，外网上传，另外一个是一样的逻辑，远程图片[微信头像url]确是秒传，两边不一样的就是内外网配置了

**Comment by zishang520** [comment]
[https://github.com/zishang520/Aliyun-oss-storage](https://github.com/zishang520/Aliyun-oss-storage)    
康康@zongmi
