### ISSUE TITLE
use League\Flysystem\Adapter\AbstractAdapter;   not  found

### ISSUE THREAD

**Issue by sanyuanya** [jacobcyl/Aliyun-oss-storage#94]
laravel 9 
php8.2.8
这个包下的已经没有这个类了

**Comment by 761042678** [comment]
最高只支持到 laravel8.*

laravel9 开始不支持了；

提示这个类没有；需要额外再安装一个 s3 的扩展包；
composer require league/flysystem-sftp-v3 "^3.0"
试试看

**Comment by sanyuanya** [comment]
感谢
